backend:
  name: github
  repo: lucasayb/lucasyamamoto.blog-v2
  branch: main
  site_domain: lucasyamamoto.netlify.com

publish_mode: editorial_workflow

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "categories"
    label: "Categories"
    folder: "categories"
    create: true
    fields: # The fields for each document, usually in front matter
      - { 
          label: "Name", 
          name: "name", 
          widget: "string" 
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        } # The fields for each document, usually in front matter
      - { 
          label: "Color", 
          name: "color", 
          widget: "color",
          allowInput: true
        }

  - name: "blog_posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Desenvolvimento",
              "DevOps",
              "Dicas",
              "Experiência",
              "Gestão de Projetos",
              "Vida",
              "Vídeos",
            ],
        }
      - {
          label: "Color",
          name: "color",
          widget: "select",
          options:
            [
              { label: "Desenvolvimento", value: "#e74c3c" },
              { label: "DevOps", value: "#9b59b6" },
              { label: "Dicas", value: "#1abc9c" },
              { label: "Experiência", value: "#341f97" },
              { label: "Gestão de Projetos", value: "#B53471" },
              { label: "Vida", value: "#6ab04c" },
              { label: "Vídeos", value: "#3498db" },
            ],
        }
      - { label: "Redirect from", name: "redirect_from", widget: "list" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
